//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service_Dagorlad
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Info", Namespace="http://schemas.datacontract.org/2004/07/Service_Dagorlad")]
    public partial class Info : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime enter_dtField;
        
        private string ipField;
        
        private bool isansweredField;
        
        private string perhabs_emailField;
        
        private string perhabs_fioField;
        
        private System.DateTime update_dtField;
        
        private string usernameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime enter_dt
        {
            get
            {
                return this.enter_dtField;
            }
            set
            {
                this.enter_dtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ip
        {
            get
            {
                return this.ipField;
            }
            set
            {
                this.ipField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isanswered
        {
            get
            {
                return this.isansweredField;
            }
            set
            {
                this.isansweredField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string perhabs_email
        {
            get
            {
                return this.perhabs_emailField;
            }
            set
            {
                this.perhabs_emailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string perhabs_fio
        {
            get
            {
                return this.perhabs_fioField;
            }
            set
            {
                this.perhabs_fioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime update_dt
        {
            get
            {
                return this.update_dtField;
            }
            set
            {
                this.update_dtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Conversations", Namespace="http://schemas.datacontract.org/2004/07/Service_Dagorlad")]
    public partial class Conversations : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime dtField;
        
        private string emailField;
        
        private System.Collections.Generic.Dictionary<string, string> files_uploadedField;
        
        private string fromField;
        
        private string groupField;
        
        private bool isonlineField;
        
        private bool isreadField;
        
        private string messageField;
        
        private string nameField;
        
        private string toField;
        
        private string uri_imagesField;
        
        private string[] whoreaded_fromField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dt
        {
            get
            {
                return this.dtField;
            }
            set
            {
                this.dtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> files_uploaded
        {
            get
            {
                return this.files_uploadedField;
            }
            set
            {
                this.files_uploadedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string from
        {
            get
            {
                return this.fromField;
            }
            set
            {
                this.fromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string group
        {
            get
            {
                return this.groupField;
            }
            set
            {
                this.groupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isonline
        {
            get
            {
                return this.isonlineField;
            }
            set
            {
                this.isonlineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isread
        {
            get
            {
                return this.isreadField;
            }
            set
            {
                this.isreadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string to
        {
            get
            {
                return this.toField;
            }
            set
            {
                this.toField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string uri_images
        {
            get
            {
                return this.uri_imagesField;
            }
            set
            {
                this.uri_imagesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] whoreaded_from
        {
            get
            {
                return this.whoreaded_fromField;
            }
            set
            {
                this.whoreaded_fromField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IService_Dagorlad")]
public interface IService_Dagorlad
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Dagorlad/TestConnection", ReplyAction="http://tempuri.org/IService_Dagorlad/TestConnectionResponse")]
    bool TestConnection();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Dagorlad/TestConnection", ReplyAction="http://tempuri.org/IService_Dagorlad/TestConnectionResponse")]
    System.Threading.Tasks.Task<bool> TestConnectionAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Dagorlad/Update", ReplyAction="http://tempuri.org/IService_Dagorlad/UpdateResponse")]
    Service_Dagorlad.Info[] Update(Service_Dagorlad.Info s);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Dagorlad/Update", ReplyAction="http://tempuri.org/IService_Dagorlad/UpdateResponse")]
    System.Threading.Tasks.Task<Service_Dagorlad.Info[]> UpdateAsync(Service_Dagorlad.Info s);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Dagorlad/AddMessage", ReplyAction="http://tempuri.org/IService_Dagorlad/AddMessageResponse")]
    void AddMessage(Service_Dagorlad.Conversations message);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Dagorlad/AddMessage", ReplyAction="http://tempuri.org/IService_Dagorlad/AddMessageResponse")]
    System.Threading.Tasks.Task AddMessageAsync(Service_Dagorlad.Conversations message);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Dagorlad/return_Conversation", ReplyAction="http://tempuri.org/IService_Dagorlad/return_ConversationResponse")]
    Service_Dagorlad.Conversations[] return_Conversation(string from, string to, string group);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Dagorlad/return_Conversation", ReplyAction="http://tempuri.org/IService_Dagorlad/return_ConversationResponse")]
    System.Threading.Tasks.Task<Service_Dagorlad.Conversations[]> return_ConversationAsync(string from, string to, string group);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Dagorlad/return_Conversation_Unreaded", ReplyAction="http://tempuri.org/IService_Dagorlad/return_Conversation_UnreadedResponse")]
    Service_Dagorlad.Conversations[] return_Conversation_Unreaded(string from, string to, string group);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Dagorlad/return_Conversation_Unreaded", ReplyAction="http://tempuri.org/IService_Dagorlad/return_Conversation_UnreadedResponse")]
    System.Threading.Tasks.Task<Service_Dagorlad.Conversations[]> return_Conversation_UnreadedAsync(string from, string to, string group);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Dagorlad/Set_Conversation_Readed", ReplyAction="http://tempuri.org/IService_Dagorlad/Set_Conversation_ReadedResponse")]
    void Set_Conversation_Readed(string from, string to, string group);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Dagorlad/Set_Conversation_Readed", ReplyAction="http://tempuri.org/IService_Dagorlad/Set_Conversation_ReadedResponse")]
    System.Threading.Tasks.Task Set_Conversation_ReadedAsync(string from, string to, string group);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IService_DagorladChannel : IService_Dagorlad, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class Service_DagorladClient : System.ServiceModel.ClientBase<IService_Dagorlad>, IService_Dagorlad
{
    
    public Service_DagorladClient()
    {
    }
    
    public Service_DagorladClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public Service_DagorladClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Service_DagorladClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Service_DagorladClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public bool TestConnection()
    {
        return base.Channel.TestConnection();
    }
    
    public System.Threading.Tasks.Task<bool> TestConnectionAsync()
    {
        return base.Channel.TestConnectionAsync();
    }
    
    public Service_Dagorlad.Info[] Update(Service_Dagorlad.Info s)
    {
        return base.Channel.Update(s);
    }
    
    public System.Threading.Tasks.Task<Service_Dagorlad.Info[]> UpdateAsync(Service_Dagorlad.Info s)
    {
        return base.Channel.UpdateAsync(s);
    }
    
    public void AddMessage(Service_Dagorlad.Conversations message)
    {
        base.Channel.AddMessage(message);
    }
    
    public System.Threading.Tasks.Task AddMessageAsync(Service_Dagorlad.Conversations message)
    {
        return base.Channel.AddMessageAsync(message);
    }
    
    public Service_Dagorlad.Conversations[] return_Conversation(string from, string to, string group)
    {
        return base.Channel.return_Conversation(from, to, group);
    }
    
    public System.Threading.Tasks.Task<Service_Dagorlad.Conversations[]> return_ConversationAsync(string from, string to, string group)
    {
        return base.Channel.return_ConversationAsync(from, to, group);
    }
    
    public Service_Dagorlad.Conversations[] return_Conversation_Unreaded(string from, string to, string group)
    {
        return base.Channel.return_Conversation_Unreaded(from, to, group);
    }
    
    public System.Threading.Tasks.Task<Service_Dagorlad.Conversations[]> return_Conversation_UnreadedAsync(string from, string to, string group)
    {
        return base.Channel.return_Conversation_UnreadedAsync(from, to, group);
    }
    
    public void Set_Conversation_Readed(string from, string to, string group)
    {
        base.Channel.Set_Conversation_Readed(from, to, group);
    }
    
    public System.Threading.Tasks.Task Set_Conversation_ReadedAsync(string from, string to, string group)
    {
        return base.Channel.Set_Conversation_ReadedAsync(from, to, group);
    }
}
